### ISSUE TITLE
Any plan on continuing development?

### ISSUE THREAD

**Issue by awesomebytes** [griganton/telepy#1]
Hello, I'm interested in a Python API for telegram, everyone seems to just go with the ugly (and buggy in my tests) CLI-based python API.

I could probably help on the development.

**Comment by griganton** [comment]
Hi! Yes, my plan is to develop MTProto/telegram API in pure python, without CLI wrapping. It is more likely educational project - I'm not so experienced developer.

First step is to khow how serialize/deserialize data. MTProto uses binary data as the base of protocol (not JSON or XML, only binary, only hardcore).https://core.telegram.org/mtproto/serialize, https://core.telegram.org/mtproto/TL

Next step is to get the authorization.
Now I am trying to implement this example: https://core.telegram.org/mtproto/samples-auth_key
Today I am on the step 4 :)

As you can see, I'm on the very beginning. Yes, you can join, sure  :)
For now, I'm looking for clear ideas how to create objects/functions, serialize and deserialize data easily with less code.

You can go to https://my.telegram.org/ and register your test app (get API keys).

**Comment by awesomebytes** [comment]
Closing this, as we are obviously working on it! :dancer:
